# Generated by Django 2.0.3 on 2018-03-26 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
