# Generated by Django 2.0.3 on 2018-04-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_posts_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='deneme',
        ),
    ]
